[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.32.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.32.3"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.32.3"

[context.stage.environment]
  HUGO_ENABLEGITINFO = "true"
