#!/usr/bin/env bash
set -e

run() {
  [ -x $1 ] && $1
}

umask 002

source $HOME/.virtualenvs/pmacio/bin/activate
make install_deploy

run deploy/before_restart
run deploy/restart && run deploy/after_restart
